### ISSUE TITLE
CONTRACTS spreadsheet: Fix column headers and form placeholders

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mPATH#4375]
Screenshot Example of VECHICLES tab

![Contracts_Vehicles_tab_column_header_and_form_label_edits](https://user-images.githubusercontent.com/11938477/168862810-80b60689-4d7d-4de3-a8ee-d303650abd25.png)

Screenshot Example of CONTRACT DETAILS tab

![Contracts_Contract-Details_tab_column_header_and_form_label_edits](https://user-images.githubusercontent.com/11938477/168862821-f50405c9-1de5-43e4-b323-b54eaef8cf3a.png)

NOTE: Also make column headers of EXPIRED CONTRACTS tab match

**Comment by juan-rivera-2020** [comment]
Fixed all issues mentioned here except "SINS/Subcategories" header.    Actual column header used by customers is "SINS/Subcategories" so I don't want to deviate.  Also, dropdown contains variation (ie, "subcategory") since selecting an item is a singular subcategory vs plural subcategories displayed in column.

**Comment by LAlexMHllc** [comment]
Closing, fixed
